name: CI on push
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run build
      with:
       registry: ghcr.io
       username: marinosefstathiou
       password: secret
       run: |
         docker build . --tag ghcr.io/marinosefstathiou/hello-docker-gcr-demo:latest
         docker run ghcr.io/marinosefstathiou/hello-docker-gcr-demo:latest
         docker push ghcr.io/marinosefstathiou/hello-docker-gcr-demo:latest
